[font]
size = 15.4

[font.normal]
family = "JetBrains Mono"

[colors]
cursor = { text = "CellBackground", cursor = "#ebdbb2" }
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#121212"
foreground = "#ebdbb2"

[colors.normal]
black   = "#121212"
red     = "#d75f5f"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#d75f5f"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.1
