if &loadplugins
  packadd! vim-closer
  packadd! vim-commentary
  packadd! vim-surround
  if has('nvim')
    packadd! nvim-lspconfig
    packadd! nvim-treesitter
    packadd! mini.completion
  else
  endif
endif

filetype plugin indent on
syntax enable
