if &loadplugins
  packadd! ReplaceWithRegister
  packadd! vim-closer
  packadd! vim-commentary
  packadd! vim-surround
  runtime! ftplugin/man.vim
  if has('nvim')
    packadd! nvim-lspconfig
    packadd! nvim-treesitter
    packadd! gruvbox.nvim
  else
    packadd! vim-lsc
  endif
endif

filetype plugin indent on
syntax enable
