alias ls="ls --color=auto --group-directories-first"
alias la="ls -a"
alias ll="ls -al"
alias grep="grep --color=auto"
alias mkdir="mkdir -p"
alias diff="diff --color=auto"
alias vim="nvim"
alias g="git"
