alias x="exit"
alias ...="cd ../.."
alias dg="git --git-dir=$HOME/dotfiles/ --work-tree=$HOME"
alias ls="ls --color=auto --group-directories-first"
alias la="ls -a"
alias ll="ls -al"
alias grep="grep --color=auto"
alias mkdir="mkdir -p"
alias diff="diff --color=auto"
alias wget="wget --hsts-file=\"$XDG_CACHE_HOME/wget-hsts\""
alias v="nvim"
alias g="git"
