alias x="exit"
alias dg="/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME"
alias ls="ls --color=yes"
alias la="ls -a"
alias ll="ls -al"
alias wget="wget --hsts-file=\"$XDG_CACHE_HOME/wget-hsts\""
alias v="nvim"
alias g="git"
