alias x="exit"
alias dg="/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME"
alias ls="ls -h --color=auto"
alias la="ls -a"
alias ll="ls -al"
alias grep="grep --color=auto"
alias mkdir="mkdir -pv"
alias diff="diff --color=auto"
alias wget="wget --hsts-file=\"$XDG_CACHE_HOME/wget-hsts\""
alias v="nvim"
alias g="git"
