source $XDG_CONFIG_HOME/nvim/general/packages.vim
source $XDG_CONFIG_HOME/nvim/general/settings.vim
source $XDG_CONFIG_HOME/nvim/general/statusline.vim
source $XDG_CONFIG_HOME/nvim/general/autocmds.vim
source $XDG_CONFIG_HOME/nvim/general/mappings/leader.vim
source $XDG_CONFIG_HOME/nvim/general/mappings/normal.vim
source $XDG_CONFIG_HOME/nvim/general/mappings/insert.vim
source $XDG_CONFIG_HOME/nvim/general/mappings/command.vim
source $XDG_CONFIG_HOME/nvim/general/netrw.vim
